# Generated by Django 5.1.3 on 2024-11-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("journal", models.CharField(max_length=255)),
                ("published_date", models.DateField()),
                ("authors", models.TextField()),
                ("institutions", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("doi", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
