# Generated by Django 5.1.3 on 2024-11-19 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="institutions",
            new_name="abstract",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="keywords",
            new_name="affiliations",
        ),
        migrations.RemoveField(
            model_name="article",
            name="link",
        ),
        migrations.RemoveField(
            model_name="article",
            name="summary",
        ),
    ]
