# Generated by Django 5.1.3 on 2024-11-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_rename_institutions_article_abstract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="published_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name="article",
            table="articles",
        ),
    ]
