# Generated by Django 5.1.3 on 2024-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_lastupdated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="affiliations",
        ),
        migrations.AddField(
            model_name="article",
            name="journal_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="doi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="journal",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
