# Generated by Django 5.1.3 on 2024-12-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_remove_article_affiliations_article_journal_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="affiliations",
            field=models.TextField(blank=True, null=True),
        ),
    ]
